### ISSUE TITLE
Locking by shaking bug/request 

### ISSUE THREAD

**Issue by Turhvjbufv** [hardalgorithm/ParanoidsPal-PrivacyLock#2]
If you have fingerprint on, locking by shaking requires you to use pin/password, which can get very annoying, if you could add a toggle that allows to use fingerprint after shaking to lock would be nice

**Comment by hardalgorithm** [comment]
Hi Turhvjbufv 👋
In the app there is a switch that turns off the “Shake & Lock” function by default it is turned off (you can also set it to fast reaction to make sure not to trigger it unintentionally)

If you mean this behavior:  `_Enable Shake Toggle_ -> _Shake device_ -> _Use Fingerprint_ -> _Lock Device_`

This scheme in my understanding of security is wrong because this shake feature is aimed at stressful situation and to shake the phone and further apply a finger requires too many actions (besides fingerprint may not work the first time).

In your case I would suggest to disable this feature and use shortcuts or quick tiles as an alternative to your method

Thanks for review if you have any more ideas I'd be happy to consider them 🤝
